/**
 * HashCoder IDE - GitHub Integration
 * 
 * Handles repository creation, commits, and pushing code
 */

export interface GitHubRepo {
    name: string;
    htmlUrl: string;
    cloneUrl: string;
}

export interface GitHubCommitResult {
    sha: string;
    message: string;
    url: string;
}

export class GitHubService {
    private token: string;
    private apiBase = 'https://api.github.com';

    constructor(token: string) {
        this.token = token;
    }

    /**
     * Create a new repository
     */
    async createRepository(name: string, isPrivate: boolean = false): Promise<GitHubRepo> {
        const response = await fetch(`${this.apiBase}/user/repos`, {
            method: 'POST',
            headers: {
                'Authorization': `token ${this.token}`,
                'Content-Type': 'application/json',
                'Accept': 'application/vnd.github.v3+json'
            },
            body: JSON.stringify({
                name,
                private: isPrivate,
                auto_init: true,
                description: `Generated by HashCoder IDE`
            })
        });

        if (!response.ok) {
            const error = await response.json();
            throw new Error(`Failed to create repository: ${error.message}`);
        }

        const data = await response.json();

        return {
            name: data.name,
            htmlUrl: data.html_url,
            cloneUrl: data.clone_url
        };
    }

    /**
     * Push files to repository
     */
    async pushFiles(
        owner: string,
        repo: string,
        files: Record<string, string>,
        message: string = 'Initial commit from HashCoder IDE'
    ): Promise<GitHubCommitResult> {
        // Get the default branch
        const repoData = await this.getRepository(owner, repo);
        const branch = repoData.default_branch || 'main';

        // Get the latest commit SHA
        const refData = await this.getReference(owner, repo, `heads/${branch}`);
        const latestCommitSha = refData.object.sha;

        // Get the base tree
        const commitData = await this.getCommit(owner, repo, latestCommitSha);
        const baseTreeSha = commitData.tree.sha;

        // Create blobs for each file
        const tree = await Promise.all(
            Object.entries(files).map(async ([path, content]) => {
                const blob = await this.createBlob(owner, repo, content);
                return {
                    path,
                    mode: '100644' as const,
                    type: 'blob' as const,
                    sha: blob.sha
                };
            })
        );

        // Create new tree
        const newTree = await this.createTree(owner, repo, tree, baseTreeSha);

        // Create commit
        const commit = await this.createCommit(owner, repo, message, newTree.sha, [latestCommitSha]);

        // Update reference
        await this.updateReference(owner, repo, `heads/${branch}`, commit.sha);

        return {
            sha: commit.sha,
            message,
            url: commit.html_url
        };
    }

    // Helper methods

    private async getRepository(owner: string, repo: string) {
        const response = await fetch(`${this.apiBase}/repos/${owner}/${repo}`, {
            headers: {
                'Authorization': `token ${this.token}`,
                'Accept': 'application/vnd.github.v3+json'
            }
        });

        if (!response.ok) throw new Error('Failed to get repository');
        return response.json();
    }

    private async getReference(owner: string, repo: string, ref: string) {
        const response = await fetch(`${this.apiBase}/repos/${owner}/${repo}/git/ref/${ref}`, {
            headers: {
                'Authorization': `token ${this.token}`,
                'Accept': 'application/vnd.github.v3+json'
            }
        });

        if (!response.ok) throw new Error('Failed to get reference');
        return response.json();
    }

    private async getCommit(owner: string, repo: string, sha: string) {
        const response = await fetch(`${this.apiBase}/repos/${owner}/${repo}/git/commits/${sha}`, {
            headers: {
                'Authorization': `token ${this.token}`,
                'Accept': 'application/vnd.github.v3+json'
            }
        });

        if (!response.ok) throw new Error('Failed to get commit');
        return response.json();
    }

    private async createBlob(owner: string, repo: string, content: string) {
        const response = await fetch(`${this.apiBase}/repos/${owner}/${repo}/git/blobs`, {
            method: 'POST',
            headers: {
                'Authorization': `token ${this.token}`,
                'Content-Type': 'application/json',
                'Accept': 'application/vnd.github.v3+json'
            },
            body: JSON.stringify({
                content,
                encoding: 'utf-8'
            })
        });

        if (!response.ok) throw new Error('Failed to create blob');
        return response.json();
    }

    private async createTree(owner: string, repo: string, tree: any[], baseTree?: string) {
        const response = await fetch(`${this.apiBase}/repos/${owner}/${repo}/git/trees`, {
            method: 'POST',
            headers: {
                'Authorization': `token ${this.token}`,
                'Content-Type': 'application/json',
                'Accept': 'application/vnd.github.v3+json'
            },
            body: JSON.stringify({
                tree,
                base_tree: baseTree
            })
        });

        if (!response.ok) throw new Error('Failed to create tree');
        return response.json();
    }

    private async createCommit(owner: string, repo: string, message: string, tree: string, parents: string[]) {
        const response = await fetch(`${this.apiBase}/repos/${owner}/${repo}/git/commits`, {
            method: 'POST',
            headers: {
                'Authorization': `token ${this.token}`,
                'Content-Type': 'application/json',
                'Accept': 'application/vnd.github.v3+json'
            },
            body: JSON.stringify({
                message,
                tree,
                parents
            })
        });

        if (!response.ok) throw new Error('Failed to create commit');
        return response.json();
    }

    private async updateReference(owner: string, repo: string, ref: string, sha: string) {
        const response = await fetch(`${this.apiBase}/repos/${owner}/${repo}/git/refs/${ref}`, {
            method: 'PATCH',
            headers: {
                'Authorization': `token ${this.token}`,
                'Content-Type': 'application/json',
                'Accept': 'application/vnd.github.v3+json'
            },
            body: JSON.stringify({
                sha,
                force: true
            })
        });

        if (!response.ok) throw new Error('Failed to update reference');
        return response.json();
    }
}
